package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"go-demo/internal/pkg/graph/models"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, title string, userID string) (*models.Task, error) {
	return r.TaskUseCase.Create(ctx, title, userID)
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, taskID string, completed bool) (*models.Task, error) {
	return r.TaskUseCase.Update(ctx, taskID, completed)
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*models.Task, error) {
	return r.TaskUseCase.List(ctx)
}
